# Generated by Django 5.1.5 on 2025-02-25 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('envA', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Brand_mapping_tracker',
        ),
    ]
