# Generated by Django 5.1.5 on 2025-02-25 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('envA', '0004_delete_brand_mapping_tracker'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('createdat', models.CharField(max_length=255)),
                ('updatedat', models.CharField(max_length=255)),
            ],
            options={
                'db_table': '"public"."Roles"',
                'managed': False,
            },
        ),
    ]
