# Generated by Django 5.1.5 on 2025-02-25 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envA', '0006_brand_mapping_tracker'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('cost', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.CharField(max_length=255)),
                ('createdat', models.CharField(max_length=255)),
                ('updatedat', models.CharField(max_length=255)),
                ('categoryid', models.CharField(max_length=255)),
            ],
            options={
                'db_table': '"public"."Products"',
                'managed': False,
            },
        ),
    ]
