# Generated by Django 5.1.5 on 2025-02-25 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('envA', '0007_products'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Roles',
        ),
    ]
