# Generated by Django 5.1.5 on 2025-02-25 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envA', '0008_delete_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pets',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('birth_date', models.CharField(max_length=255)),
                ('type_id', models.CharField(max_length=255)),
                ('owner_id', models.CharField(max_length=255)),
            ],
            options={
                'db_table': '"public"."pets"',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Brand_mapping_tracker',
        ),
        migrations.DeleteModel(
            name='Products',
        ),
    ]
