# Generated by Django 5.1.5 on 2025-02-26 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envA', '0010_vet_specialties_delete_pets'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('createdat', models.CharField(max_length=255)),
                ('updatedat', models.CharField(max_length=255)),
            ],
            options={
                'db_table': '"public"."Roles"',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Vet_specialties',
        ),
    ]
