# Generated by Django 5.1.5 on 2025-02-26 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('envA', '0011_roles_delete_vet_specialties'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Roles',
        ),
    ]
