# Generated by Django 5.1.5 on 2025-02-26 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('envA', '0016_phbas_inventory_delete_pharmacy_item'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='phbas_inventory',
            table='PH_PHARMACY.PHBAS_INVENTORY',
        ),
    ]
