# Generated by Django 5.1.5 on 2025-02-26 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('envA', '0017_alter_phbas_inventory_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='phbas_inventory',
            table='"PH_PHARMACY"."PHBAS_INVENTORY"',
        ),
    ]
