# Generated by Django 5.1.5 on 2025-02-27 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('envA', '0019_owners'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Owners',
        ),
    ]
