# Generated by Django 5.1.5 on 2025-02-27 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('envA', '0021_owners'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Owners',
        ),
        migrations.DeleteModel(
            name='Phbas_inventory',
        ),
    ]
