# Generated by Django 5.1.5 on 2025-02-27 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('envA', '0023_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Phbas_inventory',
        ),
    ]
