# Generated by Django 5.1.5 on 2025-02-27 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('envA', '0024_delete_phbas_inventory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Owners',
        ),
    ]
