# Generated by Django 5.1.5 on 2025-03-02 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envA', '0030_access_rule_access_rule_aud_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Black_list_hospital_ids',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_patient_information_id', models.CharField(max_length=255)),
                ('black_list_hospital_id', models.CharField(max_length=255)),
            ],
            options={
                'db_table': '"empi"."black_list_hospital_ids"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Migrated_patients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upi', models.CharField(max_length=255)),
                ('groupid', models.CharField(max_length=255)),
            ],
            options={
                'db_table': '"empi"."migrated_patients"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mongo_patients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upi', models.CharField(max_length=255)),
                ('groupid', models.CharField(max_length=255)),
            ],
            options={
                'db_table': '"empi"."mongo_patients"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Other_patient_ids',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=255)),
                ('other_patient_id', models.CharField(max_length=255)),
            ],
            options={
                'db_table': '"empi"."other_patient_ids"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Other_patient_mrns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merge_detail_id', models.CharField(max_length=255)),
                ('other_patient_mrn', models.CharField(max_length=255)),
            ],
            options={
                'db_table': '"empi"."other_patient_mrns"',
                'managed': False,
            },
        ),
    ]
